nelmio_api_doc:
  path: /api/v1/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_refresh_token:
  path: /api/v1/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh